### ISSUE TITLE
Assign field representation in object 

### ISSUE THREAD

**Issue by enriquemarquez** [Pablo097/hycohanz#1]
The representation of fields on different objects is an usual task in HFSS. It would be interesting the possibility of including the asignement of field representation on boxes and surfaces.

**Comment by Pablo097** [comment]
A new 'create_field_plot' has been implemented in the last commit. 
The CreateFieldPlot() HFSS function has lots of options related to the specific type of object on which to plot the fields, and related to the plot settings. Fortunately, HFSS doesn't complain if most of these parameters are not explicitly given, so I have implemented the function in the simplest way possible.
Please, give it a try and let me know if it works for you, before I close the issue.
