### ISSUE TITLE
Several integration lines in waveports

### ISSUE THREAD

**Issue by enriquemarquez** [Pablo097/hycohanz#2]
In CPW and in circular waveguides it is necesarry to establish different modes with their integration lines individually. It would be interesting the posibility of adding something like five modes in a waveport and the integration lines of two of them.

**Comment by Pablo097** [comment]
I have implemented 'assign_waveport' as a more general function, in replacement of the previous 'assign_waveport_multimode' and 'assign_waveport_intline' functions.
Now the functions allows multiple modes and integration lines for all or only some of them.
Also, notice that the previous 'assign_lumpedport_intline' is now simply called 'assign_lumpedport', as Lumped Ports only allow one mode with a required integration line.
Please, check it out and tell me if it behaves correctly for you, before closing the issue.
